name: Save PR Details

on:
  pull_request:
  
jobs:
  save-pr-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Save PR details
        env:
          PR_DETAILS: '${{ toJSON(github.event.pull_request) }}'
        run: |
          node savePrDetails.js
